#ifndef MAIN_H
#define MAIN_H

#define ESC        27   // Tecla de salida

/* variables globales */

void proc1();
void proc2();
void proc3();
void proc4();

////////////////////////////////////////////////////////////////////////////////
// #define CLK_INT    0x08 // Vector de Interrupcion

// extern int g_iTicks;
// extern int g_iSeconds;
// extern int g_bFirstRun;
// extern int g_iLastX;
// extern int g_iLastY;

// void interrupt context_switch();
////////////////////////////////////////////////////////////////////////////////

#endif
